#!/usr/bin/env python3
"""Firewall Semantic Canonicalization & Parsing Engine for M1.1 S2-D.

Implements C(F): transforms raw iptables-save output into its canonical semantic
representation, filtering out non-semantic noise (timestamps, packet/byte counters,
whitespace variation) while preserving 100% of security semantics (table order,
chain policies, rule ordering, match predicates, targets, and parameters).

FAIL-CLOSED DESIGN:
Any structural corruption, malformed table, truncated chain header, or unrecognized
syntax raises FirewallParseError immediately, preventing false-pass verdicts.
"""
from __future__ import annotations

import hashlib
from typing import List, Optional, Tuple


class FirewallParseError(ValueError):
    """Raised when firewall dump contains unparseable, malformed, or ambiguous structure."""
    pass


def canonicalize_firewall_dump(raw_dump: str) -> str:
    """Transform raw iptables-save output into its canonical semantic representation.

    Rules preserved:
      - Table declarations (*filter, *mangle, *nat, *raw) and order
      - Chain identity, order, and default policy (:CHAIN POLICY)
      - Rule order strictly preserved within each chain (NEVER SORTED)
      - Match predicates, options, interfaces, ports, states
      - Target action and parameters (-j DROP, -j ACCEPT, etc.)

    Noise stripped:
      - Comment lines (# Generated by..., # Completed on..., etc.)
      - Blank lines
      - Dynamic packet/byte counters in chain headers (:CHAIN POLICY [pkts:bytes])
      - Embedded packet counters in rules (-c <pkts> <bytes> or [pkts:bytes])
      - Redundant whitespace between tokens

    Fail-closed policy:
      - Malformed table declarations raise FirewallParseError
      - Statements outside table context raise FirewallParseError
      - Malformed chain declarations raise FirewallParseError
      - Unclosed tables (missing COMMIT before next table or EOF) raise FirewallParseError
      - Unrecognized syntax statements raise FirewallParseError
    """
    if not isinstance(raw_dump, str):
        raise FirewallParseError("Input firewall dump must be a string")

    lines = raw_dump.splitlines()
    canonical_lines: List[str] = []
    active_table: Optional[str] = None
    table_closed = True

    for line_idx, raw_line in enumerate(lines, 1):
        line = raw_line.strip()

        # 1. Skip blank lines and comments
        if not line or line.startswith("#"):
            continue

        # 2. Table declaration (*table)
        if line.startswith("*"):
            if not table_closed:
                raise FirewallParseError(
                    f"Line {line_idx}: Table {active_table} started without COMMIT of prior table"
                )
            tokens = line.split()
            if len(tokens) != 1 or len(tokens[0]) <= 1:
                raise FirewallParseError(f"Line {line_idx}: Malformed table declaration: '{line}'")
            active_table = tokens[0]
            table_closed = False
            canonical_lines.append(active_table)
            continue

        # 3. Table commit (COMMIT)
        if line == "COMMIT":
            if active_table is None or table_closed:
                raise FirewallParseError(f"Line {line_idx}: COMMIT encountered outside of table context")
            canonical_lines.append("COMMIT")
            table_closed = True
            active_table = None
            continue

        # 4. Statements must reside within an active table
        if active_table is None:
            raise FirewallParseError(f"Line {line_idx}: Statement outside of table: '{line}'")

        # 5. Chain declaration (:CHAIN_NAME POLICY [pkts:bytes])
        if line.startswith(":"):
            parts = line.split()
            if len(parts) < 2:
                raise FirewallParseError(f"Line {line_idx}: Malformed chain declaration: '{line}'")
            chain_name = parts[0]  # includes leading ':'
            policy = parts[1]      # ACCEPT, DROP, RETURN, or '-' for user chains

            # Verify counter bracket format if present: [packets:bytes]
            if len(parts) >= 3:
                counter_part = parts[2]
                if not (counter_part.startswith("[") and counter_part.endswith("]") and ":" in counter_part):
                    raise FirewallParseError(
                        f"Line {line_idx}: Malformed chain counter format: '{counter_part}'"
                    )

            # Normalize to ':CHAIN POLICY' (discarding dynamic traffic counters)
            canonical_lines.append(f"{chain_name} {policy}")
            continue

        # 6. Rule statement (-A CHAIN ... or -I CHAIN ...)
        if line.startswith("-A ") or line.startswith("-I "):
            tokens = line.split()
            if len(tokens) < 3:
                raise FirewallParseError(f"Line {line_idx}: Truncated rule statement: '{line}'")

            # Validate that rule uses known/safe command prefix
            chain_name = tokens[1]
            if not chain_name:
                raise FirewallParseError(f"Line {line_idx}: Empty chain name in rule: '{line}'")

            normalized_tokens: List[str] = []
            skip_count = 0

            # Set of recognized iptables flags/options in DROS environment
            recognized_flags = {
                "-A", "-I", "-D", "-p", "-s", "-d", "-i", "-o", "-j", "-m", "-c", "!",
                "--dport", "--sport", "--ctstate", "--mark", "--save-mark", "--restore-mark",
                "--set-xmark", "--set-mark", "--reject-with", "--to-ports", "--to-destination",
                "--to-source", "--dst-type", "--src-type", "--comment", "--state",
                "--nfmask", "--ctmask"
            }

            for i, tok in enumerate(tokens):
                if skip_count > 0:
                    skip_count -= 1
                    continue
                # Strip embedded packet counters: -c <pkts> <bytes>
                if tok == "-c" and i + 2 < len(tokens):
                    skip_count = 2
                    continue
                # Strip bracketed rule counters if prefix: [pkts:bytes]
                if tok.startswith("[") and tok.endswith("]") and ":" in tok:
                    continue

                # TC-10 Fail-Closed check: if token looks like a flag/option (- or --)
                # it must be in the recognized options set
                if tok.startswith("-") and not tok.startswith("--") and len(tok) == 2:
                    if tok not in recognized_flags:
                        raise FirewallParseError(
                            f"Line {line_idx}: Unrecognized short option '{tok}' in rule: '{line}'"
                        )
                elif tok.startswith("--"):
                    if tok not in recognized_flags:
                        raise FirewallParseError(
                            f"Line {line_idx}: Unrecognized long option '{tok}' in rule: '{line}'"
                        )

                normalized_tokens.append(tok)

            canonical_lines.append(" ".join(normalized_tokens))
            continue

        # 7. Unrecognized statement - FAIL CLOSED
        raise FirewallParseError(f"Line {line_idx}: Unrecognized iptables statement: '{line}'")

    if not table_closed:
        raise FirewallParseError(f"Table {active_table} reached EOF without COMMIT")

    return "\n".join(canonical_lines)


def compute_semantic_firewall_hash(raw_dump: str) -> str:
    """Computes deterministic SHA-256 digest of canonicalized firewall semantic state.

    Raises FirewallParseError on invalid/unparseable dump.
    """
    canonical_repr = canonicalize_firewall_dump(raw_dump)
    return hashlib.sha256(canonical_repr.encode("utf-8")).hexdigest()
