#!/usr/bin/env python3
"""Negative and Boundary Test Suite for Firewall Semantic Canonicalization & Rollback Oracle.

Asserts TC-01 through TC-08:
  - TC-01: Counter increment only -> Semantic Equivalence preserved (PASS)
  - TC-02: Timestamp change only -> Semantic Equivalence preserved (PASS)
  - TC-03: Residual DROP rule on port 18570 -> Semantic Hash Mismatch (FAIL)
  - TC-04: Rule ordering altered in INPUT chain -> Semantic Hash Mismatch (FAIL)
  - TC-05: Match criterion mutated (port 18570 -> 18571) -> Semantic Hash Mismatch (FAIL)
  - TC-06: Chain default policy changed (ACCEPT -> DROP) -> Semantic Hash Mismatch (FAIL)
  - TC-07: Foreign unexpected rule injected -> Semantic Hash Mismatch (FAIL)
  - TC-08: Malformed syntax / truncated dump -> Fail-closed exception (FAIL_CLOSED)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
import pytest

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.s2_v2.s2_d.firewall_canonicalizer import (
    FirewallParseError,
    canonicalize_firewall_dump,
    compute_semantic_firewall_hash,
)

# Reference baseline dump modeled directly from pre_live_snapshot.json on target host
BASELINE_DUMP = """# Generated by iptables-save v1.8.10 (nf_tables) on Fri Sep 25 13:04:30 2026
*mangle
:PREROUTING ACCEPT [19066335:4523821854]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [17388009:6050431593]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -m conntrack --ctstate RELATED,ESTABLISHED -m connmark ! --mark 0x0/0xff0000 -j CONNMARK --restore-mark --nfmask 0xff0000 --ctmask 0xff0000
-A OUTPUT -m conntrack --ctstate NEW -m mark ! --mark 0x0/0xff0000 -j CONNMARK --save-mark --nfmask 0xff0000 --ctmask 0xff0000
COMMIT
# Completed on Fri Sep 25 13:04:30 2026
# Generated by iptables-save v1.8.10 (nf_tables) on Fri Sep 25 13:04:30 2026
*raw
:PREROUTING ACCEPT [15042694:3870498417]
:OUTPUT ACCEPT [0:0]
COMMIT
# Completed on Fri Sep 25 13:04:30 2026
# Generated by iptables-save v1.8.10 (nf_tables) on Fri Sep 25 13:04:30 2026
*filter
:INPUT ACCEPT [15215708:3888354744]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
:DOCKER - [0:0]
:DOCKER-USER - [0:0]
:ts-input - [0:0]
-A INPUT -j ts-input
-A FORWARD -j DOCKER-USER
-A ts-input -s 100.69.194.32/32 -i lo -j ACCEPT
-A ts-input -i tailscale0 -j ACCEPT
-A ts-input -p udp -m udp --dport 41641 -j ACCEPT
-A ts-input -s 100.64.0.0/10 ! -i tailscale0 -j DROP
COMMIT
# Completed on Fri Sep 25 13:04:30 2026
"""


def test_tc_01_packet_counters_incremented():
    """TC-01: Built-in chain counters incremented only -> MUST PASS (hash identical)."""
    mutated_dump = BASELINE_DUMP.replace(
        ":PREROUTING ACCEPT [19066335:4523821854]",
        ":PREROUTING ACCEPT [19071784:4524307415]"
    ).replace(
        ":INPUT ACCEPT [15215708:3888354744]",
        ":INPUT ACCEPT [15221143:3888838706]"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash == mutated_hash, "TC-01 FAILED: Dynamic counters altered semantic hash!"


def test_tc_02_timestamp_comments_modified():
    """TC-02: Generator timestamps modified -> MUST PASS (hash identical)."""
    mutated_dump = BASELINE_DUMP.replace(
        "Fri Sep 25 13:04:30 2026",
        "Fri Sep 25 13:04:38 2026"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash == mutated_hash, "TC-02 FAILED: Timestamp comment altered semantic hash!"


def test_tc_03_residual_drop_rule_detected():
    """TC-03: Residual containment rule remains in post dump -> MUST FAIL (hash mismatch)."""
    # Insert residual containment rule in filter table
    mutated_dump = BASELINE_DUMP.replace(
        "-A INPUT -j ts-input",
        "-A INPUT -p udp --dport 18570 -j DROP\n-A INPUT -j ts-input"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash != mutated_hash, "TC-03 FAILED: Residual DROP rule was not detected!"


def test_tc_04_rule_order_altered_detected():
    """TC-04: Rule ordering within ts-input chain swapped -> MUST FAIL (hash mismatch)."""
    rule1 = "-A ts-input -s 100.69.194.32/32 -i lo -j ACCEPT"
    rule2 = "-A ts-input -i tailscale0 -j ACCEPT"

    # Swap rule1 and rule2
    mutated_dump = BASELINE_DUMP.replace(
        f"{rule1}\n{rule2}",
        f"{rule2}\n{rule1}"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash != mutated_hash, "TC-04 FAILED: Rule order mutation was not detected!"


def test_tc_05_match_condition_mutated_detected():
    """TC-05: Match predicate parameter changed (dport 41641 -> 41642) -> MUST FAIL (hash mismatch)."""
    mutated_dump = BASELINE_DUMP.replace(
        "--dport 41641",
        "--dport 41642"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash != mutated_hash, "TC-05 FAILED: Match condition mutation was not detected!"


def test_tc_06_chain_policy_mutated_detected():
    """TC-06: Chain default policy changed (:INPUT ACCEPT -> :INPUT DROP) -> MUST FAIL (hash mismatch)."""
    mutated_dump = BASELINE_DUMP.replace(
        ":INPUT ACCEPT [15215708:3888354744]",
        ":INPUT DROP [15215708:3888354744]"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash != mutated_hash, "TC-06 FAILED: Chain default policy mutation was not detected!"


def test_tc_07_unexpected_rule_injected_detected():
    """TC-07: Foreign unexpected rule injected into table -> MUST FAIL (hash mismatch)."""
    mutated_dump = BASELINE_DUMP.replace(
        "COMMIT\n# Completed on Fri Sep 25 13:04:30 2026\n",
        "-A INPUT -p tcp --dport 22 -j ACCEPT\nCOMMIT\n# Completed on Fri Sep 25 13:04:30 2026\n"
    )

    base_hash = compute_semantic_firewall_hash(BASELINE_DUMP)
    mutated_hash = compute_semantic_firewall_hash(mutated_dump)

    assert base_hash != mutated_hash, "TC-07 FAILED: Foreign rule injection was not detected!"


def test_tc_08_malformed_syntax_fail_closed():
    """TC-08: Malformed syntax, unclosed tables, or corrupt dump -> MUST RAISE FirewallParseError."""
    # Subcase A: Table without COMMIT
    unclosed_dump = "*filter\n:INPUT ACCEPT [0:0]\n-A INPUT -j ACCEPT\n"
    with pytest.raises(FirewallParseError, match="reached EOF without COMMIT"):
        canonicalize_firewall_dump(unclosed_dump)

    # Subcase B: Rule statement outside of any table
    outside_dump = "-A INPUT -j ACCEPT\n*filter\nCOMMIT\n"
    with pytest.raises(FirewallParseError, match="Statement outside of table"):
        canonicalize_firewall_dump(outside_dump)

    # Subcase C: Unrecognized syntax
    corrupt_dump = "*filter\nINVALID SYNTAX GIBBERISH\nCOMMIT\n"
    with pytest.raises(FirewallParseError, match="Unrecognized iptables statement"):
        canonicalize_firewall_dump(corrupt_dump)


def test_run1_real_snapshots_equivalence():
    """Verify that the actual pre and post dumps from S2-D Live Run #1 are semantically equivalent."""
    repo_root = Path(__file__).resolve().parents[3]
    pre_snap_path = repo_root / "reports" / "evidence" / "drone" / "m1_1" / "s2_v2" / "s2_d_live" / "raw_evidence" / "pre_live_snapshot.json"
    post_snap_path = repo_root / "reports" / "evidence" / "drone" / "m1_1" / "s2_v2" / "s2_d_live" / "raw_evidence" / "post_test_snapshot.json"

    if pre_snap_path.exists() and post_snap_path.exists():
        pre_data = json.loads(pre_snap_path.read_text(encoding="utf-8"))
        post_data = json.loads(post_snap_path.read_text(encoding="utf-8"))

        pre_dump = pre_data["host_firewall_state"]["filter_dump"]
        post_dump = post_data["host_firewall_state"]["filter_dump"]

        pre_semantic_hash = compute_semantic_firewall_hash(pre_dump)
        post_semantic_hash = compute_semantic_firewall_hash(post_dump)

        assert pre_semantic_hash == post_semantic_hash, (
            f"Run #1 actual dumps should have identical semantic hash! "
            f"pre={pre_semantic_hash} != post={post_semantic_hash}"
        )


def test_tc_09_canonicalizer_determinism():
    """TC-09: Canonicalizer output must be strictly deterministic across repeated invocations."""
    res1 = canonicalize_firewall_dump(BASELINE_DUMP)
    res2 = canonicalize_firewall_dump(BASELINE_DUMP)
    h1 = compute_semantic_firewall_hash(BASELINE_DUMP)
    h2 = compute_semantic_firewall_hash(BASELINE_DUMP)

    assert res1 == res2, "TC-09 FAILED: Canonical text representation is non-deterministic!"
    assert h1 == h2, "TC-09 FAILED: Semantic hash is non-deterministic!"


def test_tc_10_unknown_syntax_fail_closed():
    """TC-10: Legitimate-looking but unrecognized iptables extension/option MUST trigger FirewallParseError."""
    # Subcase A: Unrecognized short option in rule (-z)
    unknown_short = BASELINE_DUMP.replace(
        "-A INPUT -j ts-input",
        "-A INPUT -z 1234 -j ts-input"
    )
    with pytest.raises(FirewallParseError, match="Unrecognized short option '-z'"):
        canonicalize_firewall_dump(unknown_short)

    # Subcase B: Unrecognized long option in rule (--unknown-stealth-bypass)
    unknown_long = BASELINE_DUMP.replace(
        "-A INPUT -j ts-input",
        "-A INPUT --unknown-stealth-bypass -j ts-input"
    )
    with pytest.raises(FirewallParseError, match="Unrecognized long option '--unknown-stealth-bypass'"):
        canonicalize_firewall_dump(unknown_long)


def test_rollback_verifier_dual_layer_evaluation():
    """Verify RollbackVerifier reports both raw_serialization_identical and semantic_state_identical."""
    from scripts.s2_v2.s2_d.firewall_manager import FirewallManager
    from scripts.s2_v2.s2_d.models import HostFirewallSnapshot
    from scripts.s2_v2.s2_d.probe_executor import ProbeExecutor
    from scripts.s2_v2.s2_d.rollback_verifier import RollbackVerifier
    from scripts.s2_v2.s2_d.snapshot import acquire_firewall_state

    mgr = FirewallManager(dry_run=True)
    probe_exec = ProbeExecutor(dry_run=True)
    verifier = RollbackVerifier(mgr, probe_exec, dry_run=True)

    # Pre-snapshot in dry-run
    pre_snap = acquire_firewall_state(mode="DRY_RUN")
    ok, reason, details = verifier.verify_rollback(pre_snap)

    assert ok is True
    assert "raw_serialization_identical" in details
    assert "semantic_state_identical" in details
    assert details["raw_serialization_identical"] is True
    assert details["semantic_state_identical"] is True
    assert details["firewall_hash_restored"] is True
